[package]
name = "polkadot-runtime-common"
version = "0.8.29"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
bitvec = { version = "0.20.1", default-features = false, features = ["alloc"] }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4.13", optional = true }
rustc-hex = { version = "2.1.0", default-features = false }
serde = { version = "1.0.123", default-features = false }
serde_derive = { version = "1.0.117", optional = true }
static_assertions = "1.1.0"

sp-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
inherents = { package = "sp-inherents", git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
sp-staking = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }

pallet-authorship = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
pallet-session = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
pallet-staking = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
frame-system = {git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
pallet-vesting = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
pallet-offences = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
pallet-treasury = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-block-request-reputation" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true , branch = "bkchr-block-request-reputation" }

primitives = { package = "polkadot-primitives", path = "../../primitives", default-features = false }
libsecp256k1 = { version = "0.3.5", default-features = false, optional = true }
runtime-parachains = { package = "polkadot-runtime-parachains", path = "../parachains", default-features = false }

xcm = { path = "../../xcm", default-features = false }

[dev-dependencies]
hex-literal = "0.3.1"
keyring = { package = "sp-keyring", git = "https://github.com/paritytech/substrate", branch = "bkchr-block-request-reputation" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "bkchr-block-request-reputation" }
pallet-babe = { git = "https://github.com/paritytech/substrate", branch = "bkchr-block-request-reputation" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "bkchr-block-request-reputation" }
sp-election-providers = { git = "https://github.com/paritytech/substrate", branch = "bkchr-block-request-reputation" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", branch = "bkchr-block-request-reputation" }
pallet-staking-reward-curve = { git = "https://github.com/paritytech/substrate", branch = "bkchr-block-request-reputation" }
pallet-treasury = { git = "https://github.com/paritytech/substrate", branch = "bkchr-block-request-reputation" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "bkchr-block-request-reputation" }
trie-db = "0.22.3"
serde_json = "1.0.61"
libsecp256k1 = "0.3.5"

[features]
default = ["std"]
no_std = []
std = [
	"bitvec/std",
	"parity-scale-codec/std",
	"log",
	"rustc-hex/std",
	"serde_derive",
	"serde/std",
	"primitives/std",
	"inherents/std",
	"sp-core/std",
	"sp-api/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"pallet-session/std",
	"pallet-staking/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"pallet-vesting/std",
	"pallet-transaction-payment/std",
	"runtime-parachains/std",
	"xcm/std",
]
runtime-benchmarks = [
	"libsecp256k1/hmac",
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
